### ISSUE TITLE
Test release

### ISSUE THREAD

**Issue by tbsexton** [usnistgov/cord19-cdcs-nist#9]
For testing purposes in _other_ apps, it would be useful to have a "dummy" release that is _much_ smaller. 

E.g. in cv-py I interface with the releases page, and I'm finding need to automate installs from these releases at build time to verify everything works.

**Comment by pdessauw** [comment]
Sure, I can generate a smaller package of 500 files if it works for you. I just need a couple of additional information:
* What should be the name of the package?
* What should be the tag for this package?

**Comment by tbsexton** [comment]
sure, and even just 100 or so is fine...should be really fast to install/test. 

Name it `python-test` or something? tagged the same, no semver (dont want other things tracking it, right?).

**Comment by pdessauw** [comment]
The test release has been generated at https://github.com/usnistgov/cord19-cdcs-nist/releases/tag/test-package with 100 items.
